# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/Downloads/t1/proto/project_1/project_1.srcs/sources_1/ip/ila_elapsed/ila_elapsed.xci
# IP: The module: 'ila_elapsed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/Downloads/t1/proto/project_1/project_1.gen/sources_1/ip/ila_elapsed/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_elapsed'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/user/Downloads/t1/proto/project_1/project_1.gen/sources_1/ip/ila_elapsed/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_elapsed'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/user/Downloads/t1/proto/project_1/project_1.gen/sources_1/ip/ila_elapsed/ila_elapsed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_elapsed'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/user/Downloads/t1/proto/project_1/project_1.srcs/sources_1/ip/ila_elapsed/ila_elapsed.xci
# IP: The module: 'ila_elapsed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/Downloads/t1/proto/project_1/project_1.gen/sources_1/ip/ila_elapsed/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_elapsed'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/user/Downloads/t1/proto/project_1/project_1.gen/sources_1/ip/ila_elapsed/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_elapsed'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/user/Downloads/t1/proto/project_1/project_1.gen/sources_1/ip/ila_elapsed/ila_elapsed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_elapsed'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
